### ISSUE TITLE
FYI: Up and coming Yew version will introduce breaking changes

### ISSUE THREAD

**Issue by DevinLeamy** [hamza1311/material-yew#31]
The next version of Yew will be introducing the `BaseComponent`, which will function to replace the existing `Component` trait. Consequently, existing components will not be able to be used in `html! { ... }`.

This can be demonstrated by using `yew = { git = "https://github.com/yewstack/yew.git", features = ["csr"] }` and trying 
```rust
html! {
    <MatButton label="My Button" />
}
```

Docs for the new version: https://api.yew.rs/next/yew/prelude/trait.BaseComponent.html

p.s. This component library is exactly what I'm looking for! Thanks for building it!

**Comment by DevinLeamy** [comment]
This can be temporarily fixed with this patch in `lib.rs`
```rust
// https://stackoverflow.com/questions/23975391/how-to-convert-a-string-into-a-static-str
fn string_to_static_str(s: String) -> &'static str {
    Box::leak(s.into_boxed_str())
}

fn to_option_string(s: impl Display) -> Option<AttrValue> {
    let s = s.to_string();
    if s.is_empty() {
        None
    } else {
        Some(AttrValue::Static(string_to_static_str(s))) // <--- Problematic line
    }
}
```

**Comment by hamza1311** [comment]
Closing this as the library has been updated to next Yew version.
