### ISSUE TITLE
Support a published version of yew and publish to crates.io

### ISSUE THREAD

**Issue by torfmaster** [hamza1311/material-yew#4]
Thank you for creating this wonderful library!

Currently, yew-material relies on importing an unpublished version of yew from github as well as using a unpubllished version of yew-material from github. For enabling this library to be used I'd like to have both

* yew-material published on crates.io
* yew-material relying on a (specific) yew version which is published on crates.io

**Comment by hamza1311** [comment]
This library makes use of Yew features which are not released yet. Once, [Yew 0.18](https://github.com/yewstack/yew/milestone/6) is released to crates.io, yew-material can also be published.

**Comment by hamza1311** [comment]
It has been published to crates.io as [`material-yew`](https://crates.io/crates/material-yew)
